In [1]:
from sympy import *
import numpy as np

In [2]:
f = lambda x , y : np.array([y[1] , -y[0] - 2*E**x + 1 , -y[0] - E**x + 1])

In [4]:
y = [1 , 0 ,1]
X = [0 , 0.4 , 0.8 , 1.2 , 1.6 , 2]

In [5]:
for n in range(5) :
    h = X[n+1] - X[n]
    y = y + h * f(X[n] , y)
    print(y)

[1.0 -0.800000000000000 0.600000000000000]
[0.680000000000000 -1.99345975811302 0.00327012094349177]
[-0.117383903245206 -3.64589250090699 -0.758946250453495]
[-1.57574090360800 -5.85503247779815 -1.64003945825003]
[-3.91775389472726 -8.78716205587104 -2.59095606656488]
