In [4]:
from sympy import *
import numpy as np

In [5]:
f = lambda x , y : np.array([y[0] + 2*y[1] - 2*y[2] + E**(-x) , y[1] + y[2] - 2*E**(-x) , y[0] + 2*y[1] + E**(-x)])

In [6]:
y = [3 , -1 , 1]
X = [0 , 0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.6 , 0.7 , 0.8 , 0.9 , 1]

In [7]:
for n in range(10) :
    h = X[n+1] - X[n]
    k1 = h * f(X[n] , y)
    k2 = h * f(X[n] + h/2 , y + k1/2)
    k3 = h * f(X[n] + h/2 , y + k2/2)
    k4 = h * f(X[n] + h , y + k3)
    y = y + (k1 + 2*k2 + 2*k3 + k4)/6
    print(y)

[2.95601282574026 -1.19086301175780 1.17431207385801]
[2.82820001185963 -1.36717099782930 1.29430534821134]
[2.62300501509485 -1.53516736641082 1.35508120413242]
[2.34715282057472 -1.70213313870690 1.35096843025385]
[2.00762953453789 -1.87660335911595 1.27532971660781]
[1.61165491570122 -2.06862759016745 1.12031747660661]
[1.16664854342985 -2.29008512860921 0.876568550811491]
[0.680190344119430 -2.55506789637795 0.532825059119015]
[0.159976217088466 -2.88034678858437 0.0754658709098358]
[-0.386230482768018 -3.28594071304060 -0.512070258000589]
