In [5]:
from sympy import *
import numpy as np

In [6]:
f = lambda x , y : np.array([y[1] , y[2] , 2**x - 2*y[2] + y[1] + 2*y[0]])

In [7]:
y = [1 , 2 , 0]
X = [0 , 0.3 , 0.6 , 0.9 , 1.2 , 1.5 , 1.8 , 2.1 , 2.4 , 2.7 , 3]

In [8]:
for n in range(10) :
    h = X[n+1] - X[n]
    y = y + h * f(X[n] , y)
    print(y)

[1.6 2.  1.5]
[2.2        2.45       2.52934332]
[2.935     3.208803  3.5214523]
[3.8976409  4.26523869 4.69204161]
[5.17721251 5.67285117 6.1841918 ]
[6.87906786 7.52810871 8.13038771]
[ 9.13750047  9.96722503 10.68268909]
[12.12766798 13.17203175 14.03187158]
[16.0792775  17.38159323 18.42436844]
[21.29375547 22.90890376 24.1811976 ]
