In [10]:
from sympy import *
import numpy as np

In [11]:
f = lambda x , Y : np.array([x * Y[0] - Y[1] , Y[0] + Y[1] -1])

In [12]:
x0 = 1
y0 = np.array([-1 , 2])

In [13]:
x1 = 1.2
h0 = x1 - x0
y1 = y0 + h0 * f(x0 , y0)
y1

array([-1.6,  2. ])

In [14]:
x2 = 1.4
h1 = x2 - x1
y2 = y1 + h1 * f(x1 , y1)
y2

array([-2.384,  1.88 ])

In [15]:
x3 = 1.5
h2 = x3 - x2
y3 = y2 + h2 * f(x2 , y2)
y3

array([-2.90576,  1.7296 ])