In [6]:
import numpy as np
f = lambda x , y : np.array([y[1] , y[2] , x * y[2] - y[0]])

In [8]:
X = [-1 , -0.8 , -0.6 , -0.5]

In [10]:
y = np.array([1 , 0 , -2])
for n in range (3) :
    h = X[n + 1] - X[n]
    y = y + h * f(X[n] , y)
    print(y)

[ 1.  -0.4 -1.8]
[ 0.92  -0.76  -1.712]
[ 0.844   -0.9312  -1.70128]
